### ISSUE TITLE
VDJServer release

### ISSUE THREAD

**Issue by bcorrie** [ireceptor-plus/issues#103]
From the project DOA:

Task 1.4: Extend VDJServer User Interface
Duration M1 – M48; Task leader UTSW; Participants: All 
VDJServer is a cloud-based analysis portal for AIRR-seq data that provides access to a suite of tools for a complete analysis workflow, including modules for pre-processing and quality control of sequence reads, V(D)J gene segment assignment, repertoire characterization, and repertoire comparison. VDJServer also provides sophisticated visualizations for exploratory data analysis. It is accessible through a standard web browser via a graphical user interface designed for use by immunologists, clinicians, and bioinformatics researchers. VDJServer analysis jobs run on the high-performance computing resources at TACC. We will extend VDJServer’s user interface to incorporate the developments made through work packages WP2 through WP7.

**Comment by bcorrie** [comment]
@schristley a reminder that we have a VDJServer UI release deliverable for Month 48 so you will need to write up a deliverable report for this. Expected time frame for the report submitted to the iR+ Exec is end of November.

**Comment by schristley** [comment]
deliverable draft written and uploaded to owncloud

**Comment by bcorrie** [comment]
Done, deliverable submitted to EC through the portal.
