### ISSUE TITLE
Help with navigation of big tables

### ISSUE THREAD

**Issue by jeromejaglale** [ireceptor-plus/issues#13]
**Provide filter in columns (refine search)**
In Excel there is a feature that allows you to quickly filter the content after the search. So rows with corresponding data are shown and rows that do not contain the data are hidden.

**Sortable columns**
Allow user to reorder columns by drag and drop

**Make headings, rows, columns and individual cells pinnable**
If a column/row is pinned, they are always displayed, even if they actually run out of the viewport.

**Display density**
User can choose the display density (more data or more space between rows)

**Individual diagrams**
Possibility to create individual diagrams (bar chart, pie charts…) for selected cells and a fast export (e.g pdf)

**Two layer tables**
Make future tabs scrollable over another tab

**Pivot Tables**
Pivot tables summarize underlying larger tables. So they allow to go really deeper into datasets and you can gain multiple levels of details of data

**Resizable columns**
Like in Excel - table columns should be resizable by the user (simple dragging) 
 
**Align numbers to the right, text to the left**
 
**Highlight row with mouseover**

**Export to csv** 
Give the user the chance to work with it locally
 
**Show x results dropdown**
Next to pagination. Let the user choose how big the table should be.
 
**Visual Query Builder**
e.g. chartio.com/product/visual-sql/
 
**Scroll horizontally through table**
https://datatables.net/extensions/fixedcolumns/examples/initialisation/two_columns.html

**Comment by bcorrie** [comment]
Partially addressed, remainder of issues added as iReceptor issue IR-2938. Closing.
