### ISSUE TITLE
Implement ADC API on ImmuneDB

### ISSUE THREAD

**Issue by bcorrie** [ireceptor-plus/issues#18]
Need to have an ImmuneDB repository that implements the ADC API so we can query it from the iReceptor Gateway.

**Comment by bcorrie** [comment]
@areensh @systemimmunologylab we haven't heard from you for some time about the status of ImmuneDB's implementation of the ADC API. I need to report on repository statuses - can you let me know where things are at?

**Comment by bcorrie** [comment]
@areensh @systemimmunologylab I just tried to test the Haifa ADC API and I am still unable to connect:

$ curl http://systemali.haifa.ac.il:8081/frontend/immunedb_paper/airr/v1/info
curl: (7) Failed to connect to systemali.haifa.ac.il port 8081: Connection refused

Any insights?

**Comment by areensh** [comment]
Hi Brian,

Yes i am aware of that.
The IT department are making some work with servers and the internal
storages .
I will update you once it’s done . I believe by end of tomorrow.


Best

Areen

**Comment by systemimmunologylab** [comment]
it’s bad luck. We are installing some new hard drives in the server.
had you tried to access it before and it worked? or was this your 1st attempt

Uri

**Comment by bcorrie** [comment]
My attempts to date have not yet worked... There was something not working before the server update I believe

**Comment by systemimmunologylab** [comment]
did you try since our last discussion, before the day before yesterday?
Areen can  you make sure this is online ASAP and then contact brian directly,
Brian, last time you tried to use the database was the lack of response similar  to the one you got yesterday? (When the server was down for repairs) or was it something else?

best
Uri

**Comment by bcorrie** [comment]
All of my attempts have been the same error - the repository was not responding to connections at all (server down???).

**Comment by bcorrie** [comment]
Partial implementation reported on in Deliverable, project completed - closing this issue.
