### ISSUE TITLE
gene_usage analysis end point integrated with Gateway

### ISSUE THREAD

**Issue by schristley** [ireceptor-plus/issues#41]
@bcorrie There is now a working gene_usage analysis end point. Do you think you will attempt to do a simple integration with the Gateway before M24? I'm mainly asking about whether I should devote more time/effort to this right now? If no, then I can set this aside until after M24 and devote the time towards Stats API work.

Awhile back I think I created a JIRA ticket about this but I've lost track, but the basic workflow is the same.

1. Get a (VDJServer) Tapis token.
2. Upload data files, 1 repertoire and 1 rearrangement
3. Call gene_usage end point with files
4. Wait for job to finish
5. Access output data

**Comment by bcorrie** [comment]
I also think for M24 we would be better served to have a broad integration implemented, with each service implemented by at least one repository/server. Given that we will have a Stats API implementation (which we can use to demonstrate that API) on one of the iReceptor repositories (it is essentially working now in alpha) it might be better to have you work on the analysis API side so we have both covered???

That is you do Analysis, we do Stats, and then we have both covered...

**Comment by schristley** [comment]
> it might be better to have you work on the analysis API side so we have both covered???

Ok, I can certainly work on filling out the API with more analysis end points.

**Comment by bcorrie** [comment]
@schristley if I wanted to give this a try, how would I go about getting a Tapis token to use the API. I have the account info for the irplus Tapis account.

**Comment by schristley** [comment]
Send a POST request to the [token endpoint](https://bitbucket.org/vdjserver/vdjserver-web-api/src/5339bf4491602e5c51b3906444316926c149c46e/swagger/vdjserver-api.yaml#lines-278) with `username` and `password`. For example, like this:

```
curl -k --data '{"username":"johndoe","password":"abc123"}' -H 'content-type: application/json' https://vdj-staging.tacc.utexas.edu/api/v2/token
```

In the return data, the token is in `access_token` field.

**Comment by schristley** [comment]
@bcorrie You can get a token at any time because that's coming from the VDJServer API. However, give me a heads up before actually trying to use the analysis API. The service is not running at the moment, but I should be able to bring it up quickly if need be.

**Comment by schristley** [comment]
iR+ won't be providing an analysis API service, so this issue is no longer valid. There is a Tapis app for calculating gene usage as well as the Stats API.
