### ISSUE TITLE
Browsers have security that prevents mixed security content

### ISSUE THREAD

**Issue by schristley** [ireceptor-plus/issues#42]
This is a followup to the [CORS issue](https://github.com/ireceptor-plus/WP2/issues/13). Some browsers, like Safari, do not allow an `https` website to perform AJAX calls to non-secure `http` sites. For example, Safari gives an error like this:

```
[blocked] The page at https://vdj-dev.tacc.utexas.edu/community/ was not allowed to display insecure content from http://ipa5.ireceptor.org/airr/v1/info
```

Unfortunately, Safari doesn't allow this to be disabled. This is an issue because all of VDJServer is `https` while the IPA repositories are mixed security, i.e. some are `https` and some are `http`

According to @bzimonja 

> we can't figure a good way to package an SSL cert with a turnkey that will run on any domain, so we use http for now.

Even though packaging an SSL cert is an issue, in theory a lab putting up a turnkey repository should be able to get a valid SSL cert and install it.

I suppose my main question is, should we require `https` for all iR+ repositories? What about ADC in general?

**Comment by schristley** [comment]
@bcorrie With the PHP security updates, will you be enabling https for the remaining repositories?

**Comment by bcorrie** [comment]
HTTPS now a strong recommendation in the AIRR Standard and ADC API docs, with the iReceptor v4.0 release (http://www.ireceptor.org/ireceptor-4) all iReceptor repositories are HTTPS and the iReceptor Turnkey supports https with self-signed certs out of the box. Closing this issue.
