### ISSUE TITLE
Analysis API YAML not passing validity check

### ISSUE THREAD

**Issue by bcorrie** [ireceptor-plus/issues#56]
I added an automatic sanity check to the OpenAPI specs, and for some reason the analysis YAML file is not passing. I can't figure out why - any thoughts...

**Comment by bcorrie** [comment]
@schristley the badge is on the README page for the APIs here: https://github.com/ireceptor-plus/specifications/blob/master/README.md 

When I view it in the Swagger editor it doesn't generate any errors.

**Comment by schristley** [comment]
@bcorrie Don't know, I tried the /debug end point but it doesn't give any information.

**Comment by schristley** [comment]
@bcorrie It works when url encoding the request, updated the readme page.
