### ISSUE TITLE
Implement Security Layer

### ISSUE THREAD

**Issue by alxcost** [ireceptor-plus/issues#70]
- [x] Provide a framework for securing an ADC-compliant repository
- [x] Backoffice/frontend interface for Data Stewards for managing accessibility

### Details on the Security Framework
**See chapter Security Framework in**: https://ireceptorplus.inesctec.pt/wiki/start
### Development source-code:
https://github.com/ireceptorplus-inesctec/adc-middleware
### Published releases:
https://hub.docker.com/repository/docker/irpinesctec/adc-middleware

**Comment by bcorrie** [comment]
Moved to M42 and added External label as per SciTech discussion

**Comment by alxcost** [comment]
Security Framework provided by the adc-middleware, published on:
https://github.com/ireceptorplus-inesctec/adc-middleware
https://hub.docker.com/repository/docker/irpinesctec/adc-middleware

Data Steward's interface published on:
https://github.com/ireceptorplus-inesctec/acl-dashboard
https://hub.docker.com/repository/docker/irpinesctec/acl-dashboard
