### ISSUE TITLE
Blockchain-based Auditing Prototype

### ISSUE THREAD

**Issue by alxcost** [ireceptor-plus/issues#71]
Implement a blockchain-based Auditing Prototype

Simulation of a Blockchain Incentive System to Support Auditing of Traceability Data: https://drive.google.com/file/d/1nHRpzCRjRwYXmyio7XpmyEBqMGpefs1e/view?usp=sharing

**Comment by bcorrie** [comment]
Moved to Milestone M42, add External label as per SciTech discussion

**Comment by bcorrie** [comment]
Opps, removed External label, this does not require EC reporting - correct me if I am wrong...

**Comment by alxcost** [comment]
Blockchain-based prototype provided in:
https://github.com/ireceptorplus-inesctec/ireceptorchain

Along with the companion services for managing files:
Service: https://github.com/ireceptorplus-inesctec/storage-service
User Interface: https://github.com/ireceptorplus-inesctec/storage-service-ui
