### ISSUE TITLE
Basic analysis tools integrated

### ISSUE THREAD

**Issue by bcorrie** [ireceptor-plus/issues#79]

**Comment by schristley** [comment]
These are two tapis apps defined and publicly published; they can be run on the VDJServer tenant.

- irplus-statistics-stampede2-0.1u1
- assign-clones-stampede2-0.1u1

**Comment by bcorrie** [comment]
Current set of analysis tools integrated into the iReceptor Gateway are here: 

https://github.com/sfu-ireceptor/gateway/tree/analysis/resources/agave_apps

The Apps are contained in the Gateway for now - might need to change that in the future.

**Comment by schristley** [comment]
draft deliverable written and uploaded to owncloud

**Comment by bcorrie** [comment]
Done, deliverable submitted to EC through the portal.
