### ISSUE TITLE
clonal assignment app in Tapis

### ISSUE THREAD

**Issue by schristley** [ireceptor-plus/issues#81]
The app should have flexibility in the clonal definition and support human/mouse.

- [x] B cell clonal assignment.
- [x] T cell clonal assignment.

Initially one tool for each; we can consider multiple tools later.

**Comment by schristley** [comment]
created new app `assign-clones` on its own branch in tapis with same name. I cannot find my version of `find_threshold.R` so I guess I need rewrite it before the app will work.

**Comment by bcorrie** [comment]
@schristley I am cleaning up Milestones, can we mark this as closed or move it to another milestone.

**Comment by schristley** [comment]
Done, in tapis repository
