### ISSUE TITLE
Query error on VDJServer for sample.collection_time_point_relative

### ISSUE THREAD

**Issue by bcorrie** [ireceptor-plus/issues#98]
It looks like this is using the master spec - where this is an ontology field. The Gateway is (or should be) sending queries based on the 1.3.1 released spec (for the most part 8-). I say for the most part, because we have actually added fields from master that don't break backwards compatibility, but this one breaks backwards compatibility - which requires a DB upgrade - which we only do on AIRR standard releases.

We had a query error from a user that was searching on this field from the Gateway.

**Comment by bcorrie** [comment]
This is the query from the Gateway - someone looking for data from time point 0

```
{
    "filters": {
        "op": "and",
        "content": [

[Stuff deleted]

            {
                "op": "contains",
                "content": {
                    "field": "sample.collection_time_point_relative",
                    "value": "0"
                }
            }
        ]
    }
}
```

**Comment by schristley** [comment]
I've backported the openapi V3 AIRR specs to the 1.3 schema. It's currently running on VDJServer and the above query works properly.

**Comment by schristley** [comment]
@bcorrie Query working as expected on the gateway?
